// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Superfine1 = require("./superfine1");

function h(prim, prim$1, prim$2) {
  return Superfine1.h(prim, prim$1, prim$2);
}

function patch(prim, prim$1, prim$2) {
  Superfine1.patch(prim, prim$1, prim$2);
  return /* () */0;
}

function hh(tag, props, children) {
  return Superfine1.h(tag, $$Array.of_list(props), $$Array.of_list(children));
}

function app(param) {
  var node = param[/* node */3];
  var view = param[/* view */2];
  var update = param[/* update */1];
  var state = /* record */[/* contents */Curry._1(param[/* init */0], /* () */0)];
  var set_state = function (next_state) {
    state[0] = next_state;
    var dispatch = function (msg) {
      return (function (param) {
          return set_state(Curry._2(update, state[0], msg));
        });
    };
    patch(node, Curry._1(view, state[0]), dispatch);
    return /* () */0;
  };
  return set_state(state[0]);
}

var App = /* module */[
  /* h */h,
  /* patch */patch,
  /* hh */hh,
  /* app */app
];

function init(param) {
  return 0;
}

function update(state, param) {
  return state + 1 | 0;
}

function view(state) {
  return hh("div", /* :: */[
              /* Attr */Block.__(0, [/* tuple */[
                    "id",
                    "hello"
                  ]]),
              /* [] */0
            ], /* :: */[
              hh("div", /* :: */[
                    /* Attr */Block.__(0, [/* tuple */[
                          "id",
                          "naber"
                        ]]),
                    /* [] */0
                  ], /* :: */[
                    /* Text */[String(state)],
                    /* [] */0
                  ]),
              /* :: */[
                hh("button", /* :: */[
                      /* Attr */Block.__(0, [/* tuple */[
                            "id",
                            "btn-inc"
                          ]]),
                      /* :: */[
                        /* Handler */Block.__(1, [/* tuple */[
                              "onclick",
                              /* Increment */0
                            ]]),
                        /* [] */0
                      ]
                    ], /* :: */[
                      /* Text */["+"],
                      /* [] */0
                    ]),
                /* [] */0
              ]
            ]);
}

app(/* record */[
      /* init */init,
      /* update */update,
      /* view */view,
      /* node */document.getElementById("app")
    ]);

exports.App = App;
exports.init = init;
exports.update = update;
exports.view = view;
/*  Not a pure module */
