// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Hyperapp = require("hyperapp");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function increment(state, param) {
  return state + 1 | 0;
}

function decrement(state, param) {
  return state - 1 | 0;
}

function set(state, num) {
  if (num !== undefined) {
    return num[/* num */0];
  } else {
    return state;
  }
}

function multiply(state, param) {
  if (param !== undefined) {
    return Caml_int32.imul(state, param);
  } else {
    return state;
  }
}

var x = /* tuple */[
  increment,
  undefined
];

var y = /* tuple */[
  set,
  42
];

function update(param, state) {
  return Curry._2(param[0], state, param[1]);
}

var state = update(/* tuple */[
      set,
      /* record */[/* num */42]
    ], 10);

var next_state = update(/* tuple */[
      increment,
      undefined
    ], state);

console.log(next_state);

function hh(tag, props, children) {
  return Hyperapp.h(tag, props, $$Array.of_list(children));
}

function view(state) {
  return hh("div", {
              id: "naber"
            }, /* :: */[
              hh("div", {
                    id: "ahmet"
                  }, /* :: */[
                    /* Text */[String(state)],
                    /* [] */0
                  ]),
              /* :: */[
                hh("button", {
                      id: "mehmet",
                      onclick: /* tuple */[
                        increment,
                        undefined
                      ]
                    }, /* :: */[
                      /* Text */["+"],
                      /* [] */0
                    ]),
                /* :: */[
                  hh("button", {
                        id: "ayse",
                        onclick: /* tuple */[
                          decrement,
                          undefined
                        ]
                      }, /* :: */[
                        /* Text */["-"],
                        /* [] */0
                      ]),
                  /* :: */[
                    hh("button", {
                          id: "fatme",
                          onclick: /* tuple */[
                            set,
                            /* record */[/* num */42]
                          ]
                        }, /* :: */[
                          /* Text */["Set to 42"],
                          /* [] */0
                        ]),
                    /* :: */[
                      hh("button", {
                            id: "geysa",
                            onclick: /* tuple */[
                              multiply,
                              2
                            ]
                          }, /* :: */[
                            /* Text */["mult * 2"],
                            /* [] */0
                          ]),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]);
}

Hyperapp.app({
      init: 0,
      view: view,
      node: document.getElementById("app")
    });

var init = 0;

exports.increment = increment;
exports.decrement = decrement;
exports.set = set;
exports.multiply = multiply;
exports.x = x;
exports.y = y;
exports.update = update;
exports.hh = hh;
exports.init = init;
exports.view = view;
/* state Not a pure module */
